apiVersion: v1
kind: Service
metadata:
  name: addressbook-loadbalancer
  labels:
    service-type: production
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: addressbook-pods
